$schema: 1.0
tasks:
  - name: install-azdev
    description: Install azdev CLI extension development tool
    parameters:
      command: powershell
      script: pip install azdev
      runAsUser: true
